import React, { useState, useEffect, useMemo } from 'react';

// Color helper based on score
function getScoreColors(score) {
  if (score >= 80) {
    return {
      text: 'text-green-400',
      stroke: '#22c55e',
      bg: 'bg-green-500/10 border-green-500/20'
    };
  } else if (score >= 60) {
    return {
      text: 'text-amber-400',
      stroke: '#eab308',
      bg: 'bg-amber-500/10 border-amber-500/20'
    };
  } else {
    return {
      text: 'text-red-400',
      stroke: '#ef4444',
      bg: 'bg-red-500/10 border-red-500/20'
    };
  }
}

// Single SVG Score Ring Component
function ScoreRing({ label, score, delay }) {
  const [animate, setAnimate] = useState(false);
  const radius = 32;
  const circumference = 2 * Math.PI * radius; // ~201.06

  useEffect(() => {
    // Small timeout to trigger transition after render
    const t = setTimeout(() => setAnimate(true), 50);
    return () => clearTimeout(t);
  }, []);

  const { text, stroke } = getScoreColors(score);
  const strokeDashoffset = animate ? circumference - (score / 100) * circumference : circumference;

  return (
    <div className="flex flex-col items-center gap-2 bg-slate-900 border border-slate-950 p-4 rounded-xl shadow-xs">
      <div className="relative h-20 w-20 flex items-center justify-center">
        <svg className="absolute inset-0 transform -rotate-90" width="80" height="80" viewBox="0 0 80 80">
          {/* Back track */}
          <circle
            cx="40"
            cy="40"
            r={radius}
            fill="none"
            stroke="#1e293b"
            strokeWidth="5"
          />
          {/* Colored arc */}
          <circle
            cx="40"
            cy="40"
            r={radius}
            fill="none"
            stroke={stroke}
            strokeWidth="5"
            strokeDasharray={circumference}
            strokeDashoffset={strokeDashoffset}
            strokeLinecap="round"
            style={{
              transition: 'stroke-dashoffset 800ms cubic-bezier(0.4, 0, 0.2, 1)',
              transitionDelay: `${delay}ms`
            }}
          />
        </svg>
        <span className={`text-lg font-extrabold ${text}`}>
          {score}
        </span>
      </div>
      <span className="text-4xs font-bold uppercase tracking-wider text-slate-400">
        {label}
      </span>
    </div>
  );
}

export default function Scorecard({ scorecard = {} }) {
  const {
    grammar = { score: 0, feedback: '', examples: [] },
    vocabulary = { score: 0, feedback: '', level: 'basic' },
    structure = { score: 0, feedback: '', has_intro: false, has_conclusion: false },
    confidence = { score: 0, feedback: '', hedging_words: [] },
    overall_score = 0,
    top_strength = '',
    top_improvement = '',
    wpm = 0,
    filler_counts = {},
    duration_seconds = 0,
    word_count = 0
  } = scorecard;

  // State for overall score count-up
  const [displayScore, setDisplayScore] = useState(0);

  useEffect(() => {
    let start = 0;
    const end = overall_score;
    if (start === end) return;

    const duration = 1000;
    const steps = Math.min(end, 60);
    const stepIncrement = Math.ceil(end / steps);
    const incrementTime = duration / steps;

    const timer = setInterval(() => {
      start += stepIncrement;
      if (start >= end) {
        start = end;
        clearInterval(timer);
      }
      setDisplayScore(start);
    }, incrementTime);

    return () => clearInterval(timer);
  }, [overall_score]);

  // Overall score colors
  const { text: overallColorText, bg: overallBg } = getScoreColors(overall_score);

  // Parse filler list and calculate percentages
  const fillerList = useMemo(() => {
    const totalFillers = Object.values(filler_counts).reduce((sum, v) => sum + v, 0);
    if (totalFillers === 0) return [];

    return Object.entries(filler_counts)
      .map(([word, count]) => {
        const pct = word_count > 0 ? (count / word_count) * 100 : 0;
        return { word, count, percentage: pct };
      })
      .sort((a, b) => b.count - a.count);
  }, [filler_counts, word_count]);

  return (
    <div className="bg-slate-800 border border-slate-700/60 rounded-2xl p-6 shadow-xl w-full text-left flex flex-col gap-6">
      <div className="border-b border-slate-700/60 pb-3">
        <h3 className="font-bold text-slate-200 text-sm">
          Performance Scorecard
        </h3>
        <p className="text-3xs text-slate-500 mt-0.5">
          Comprehensive review generated by our Speech AI model
        </p>
      </div>

      {/* Main Grid: Overall Score + Category Rings */}
      <div className="grid grid-cols-1 md:grid-cols-12 gap-6 items-center">
        {/* Overall Score Circle (4/12 cols) */}
        <div className={`md:col-span-4 flex flex-col items-center justify-center p-6 border rounded-2xl text-center min-h-[190px] shadow-inner transition-all ${overallBg}`}>
          <span className="text-4xs font-extrabold uppercase tracking-widest text-slate-400">
            Overall Score
          </span>
          <span className={`text-6xl font-black tracking-tight ${overallColorText} mt-2 select-none`}>
            {displayScore}
          </span>
          <span className="text-4xs font-bold text-slate-500 mt-2 uppercase tracking-wide">
            out of 100 points
          </span>
        </div>

        {/* Category Rings (8/12 cols) */}
        <div className="md:col-span-8 grid grid-cols-2 sm:grid-cols-4 gap-4">
          <ScoreRing label="Grammar" score={grammar.score} delay={0} />
          <ScoreRing label="Vocabulary" score={vocabulary.score} delay={100} />
          <ScoreRing label="Structure" score={structure.score} delay={200} />
          <ScoreRing label="Confidence" score={confidence.score} delay={300} />
        </div>
      </div>

      {/* Strengths & Improvements */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        {/* Strength callout */}
        <div className="bg-green-500/5 border border-green-500/10 p-4 rounded-xl flex items-start gap-3">
          <div className="p-1.5 bg-green-500/10 border border-green-500/25 rounded-lg text-green-400 shrink-0">
            <svg className="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth="2.5">
              <path strokeLinecap="round" strokeLinejoin="round" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
            </svg>
          </div>
          <div>
            <h4 className="text-2xs font-bold uppercase tracking-wider text-green-400">Key Strength</h4>
            <p className="text-xs text-slate-300 mt-1 leading-relaxed">{top_strength || 'Clear speech and delivery.'}</p>
          </div>
        </div>

        {/* Improvement callout */}
        <div className="bg-amber-500/5 border border-amber-500/10 p-4 rounded-xl flex items-start gap-3">
          <div className="p-1.5 bg-amber-500/10 border border-amber-500/25 rounded-lg text-amber-400 shrink-0">
            <svg className="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth="2.5">
              <path strokeLinecap="round" strokeLinejoin="round" d="M13 10V3L4 14h7v7l9-11h-7z" />
            </svg>
          </div>
          <div>
            <h4 className="text-2xs font-bold uppercase tracking-wider text-amber-400">Top Improvement</h4>
            <p className="text-xs text-slate-300 mt-1 leading-relaxed">{top_improvement || 'Minimize filler phrase pauses.'}</p>
          </div>
        </div>
      </div>

      {/* Category feedbacks */}
      <div className="bg-slate-900 border border-slate-950 p-5 rounded-xl space-y-4 text-xs">
        <h4 className="font-bold text-slate-200 uppercase tracking-wider border-b border-slate-800 pb-2 text-2xs">
          Coaching Feedback Summary
        </h4>
        
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          <div className="space-y-1">
            <p className="text-slate-400 font-semibold">Grammar & Syntax:</p>
            <p className="text-slate-300 leading-relaxed">{grammar.feedback}</p>
            {grammar.examples && grammar.examples.length > 0 && (
              <div className="mt-1.5 pl-3 border-l-2 border-slate-700 italic text-slate-400 text-3xs">
                Examples: {grammar.examples.map(ex => `"${ex}"`).join(', ')}
              </div>
            )}
          </div>
          
          <div className="space-y-1">
            <p className="text-slate-400 font-semibold">Vocabulary Range (Level: <span className="text-indigo-400 capitalize">{vocabulary.level}</span>):</p>
            <p className="text-slate-300 leading-relaxed">{vocabulary.feedback}</p>
          </div>

          <div className="space-y-1">
            <p className="text-slate-400 font-semibold">Speech Structure:</p>
            <p className="text-slate-300 leading-relaxed">{structure.feedback}</p>
            <div className="flex gap-4 text-3xs font-semibold mt-1">
              <span className={structure.has_intro ? 'text-green-400' : 'text-slate-500'}>
                {structure.has_intro ? '✓ Contains Intro' : '✗ Missing Intro'}
              </span>
              <span className={structure.has_conclusion ? 'text-green-400' : 'text-slate-500'}>
                {structure.has_conclusion ? '✓ Contains Conclusion' : '✗ Missing Conclusion'}
              </span>
            </div>
          </div>

          <div className="space-y-1">
            <p className="text-slate-400 font-semibold">Confidence & Hedging:</p>
            <p className="text-slate-300 leading-relaxed">{confidence.feedback}</p>
            {confidence.hedging_words && confidence.hedging_words.length > 0 && (
              <div className="mt-1 flex flex-wrap gap-1 text-3xs">
                <span className="text-slate-500 font-bold mr-1">Hedging words:</span>
                {confidence.hedging_words.map((w, idx) => (
                  <span key={idx} className="bg-slate-800 text-slate-400 px-1.5 py-0.5 rounded border border-slate-750">
                    {w}
                  </span>
                ))}
              </div>
            )}
          </div>
        </div>
      </div>

      {/* Filler Frequency Table */}
      {fillerList.length > 0 && (
        <div className="bg-slate-900 border border-slate-950 p-5 rounded-xl text-xs flex flex-col gap-3">
          <h4 className="font-bold text-slate-200 uppercase tracking-wider border-b border-slate-800 pb-2 text-2xs">
            Filler Word Frequencies
          </h4>
          <div className="overflow-x-auto">
            <table className="w-full text-left">
              <thead>
                <tr className="text-4xs uppercase tracking-wider text-slate-500 border-b border-slate-800">
                  <th className="pb-2 font-bold">Word</th>
                  <th className="pb-2 font-bold text-center">Count</th>
                  <th className="pb-2 font-bold text-right">Density</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-800">
                {fillerList.map((item, idx) => (
                  <tr key={idx} className="text-slate-300">
                    <td className="py-2.5 font-semibold text-amber-300 capitalize">{item.word}</td>
                    <td className="py-2.5 text-center font-bold">{item.count}</td>
                    <td className="py-2.5 text-right font-medium">
                      <div className="inline-flex items-center gap-2">
                        <span>{item.percentage.toFixed(1)}%</span>
                        <div className="w-16 bg-slate-800 h-1.5 rounded-full overflow-hidden border border-slate-750">
                          <div
                            className="bg-amber-400 h-full rounded-full"
                            style={{ width: `${Math.min(100, item.percentage * 5)}%` }}
                          />
                        </div>
                      </div>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      )}
    </div>
  );
}
